export {
  SCENARIO_COLOURS,
  ZONE_COLOURS,
  TYPOLOGY_COLOURS,
  COVERAGE_TIERS,
  LISA_COLOURS,
  TRUST_STATE_LABELS,
} from '../data/constants';

export const NIGERIA_GREEN = '#006633';
export const NIGERIA_GREEN_DARK = '#003d1e';
export const NIGERIA_GREEN_LIGHT = '#008744';
